### ISSUE TITLE
Lord serve not working?

### ISSUE THREAD

**Issue by samarpan-rai** [koaning/skedulord#28]
I tried running `lord serve --host 0.0.0.0 --port 8080` but I cannot find the dashboard in the allocated location. Is this broken atm? I have run the command in ubuntu and raspberry pi but I see 404 page not found.

**Comment by koaning** [comment]
It might be broken ... haven't used that feature in ... a year? 

You can still get the overview from the commandline? I was thinking of dropping support for the server anyway since it mainly adds a security issue and doesn't really offer that many features.

**Comment by koaning** [comment]
I mean ... that's what dependabot keeps telling me 

![image](https://user-images.githubusercontent.com/1019791/95587136-f4bb4e00-0a41-11eb-8be9-064e9c692e80.png)

**Comment by samarpan-rai** [comment]
> It might be broken ... haven't used that feature in ... a year?
> 
> You can still get the overview from the commandline? I was thinking of dropping support for the server anyway since it mainly adds a security issue and doesn't really offer that many features.

I think the webserver adds an easy way to view the logs of all the jobs so I could help to debug it. However,  if you are planning to drop support then that would be in vain, I suppose.

**Comment by koaning** [comment]
I'm wondering. 

If you go to the logs directory and run `python3.7 -m http.server` don't you then also get the logfiles?

**Comment by koaning** [comment]
One thing; could you share the output of the command as well as the URL that you've tried?

**Comment by samarpan-rai** [comment]
> If you go to the logs directory and run python3.7 -m http.server don't you then also get the logfiles?

Where exactly is the log directory?

**Comment by samarpan-rai** [comment]
> One thing; could you share the output of the command as well as the URL that you've tried?

The output:
![afbeelding](https://user-images.githubusercontent.com/47146983/95659732-615a4980-0b23-11eb-91c3-d3f8403018dd.png)

I visited localhost, 127.0.0.1 and my local ip address with port 8080. All of them show the same result. 
![Screenshot at 2020-10-10 18-09-06](https://user-images.githubusercontent.com/47146983/95659787-bdbd6900-0b23-11eb-99d9-b52522bf4f5e.png)
![Screenshot at 2020-10-10 18-08-58](https://user-images.githubusercontent.com/47146983/95659788-be55ff80-0b23-11eb-9f55-17b5f7db8967.png)
![Screenshot at 2020-10-10 18-08-44](https://user-images.githubusercontent.com/47146983/95659789-beee9600-0b23-11eb-9121-fb4bf632049e.png)

**Comment by koaning** [comment]
Considering that you have `host=0.0.0.0` shouldn't you try the `http://0.0.0.0:8080` address?

**Comment by koaning** [comment]
The base log directory should be `~/.skedulord ` from the top of my head.

**Comment by samarpan-rai** [comment]
> Considering that you have `host=0.0.0.0` shouldn't you try the `http://0.0.0.0:8080` address?

I am not a network expert but if I understand correctly, listening on host 0.0.0.0 emits it to all IP address which should also include localhost, 127.0.0.1 and local ip address. 

Just to be sure, I visited the address and I see the same result.

![afbeelding](https://user-images.githubusercontent.com/47146983/95661584-c0728b00-0b30-11eb-8961-106678f5fb47.png)

Does it work locally on your computer with the latest pypi version?

**Comment by samarpan-rai** [comment]
> I'm wondering.
> 
> If you go to the logs directory and run `python3.7 -m http.server` don't you then also get the logfiles?

If you mean by log files the heartbeats.jsonl and the `jobs` directory then, yes.

![afbeelding](https://user-images.githubusercontent.com/47146983/95661621-0fb8bb80-0b31-11eb-8bf6-deebfa0af28e.png)

**Comment by koaning** [comment]
Mhm ... strange. I'm open to a fix. But I would say that this project has a low priority on my side.

**Comment by samarpan-rai** [comment]
The culprit seems to be `gatsby`. When you do `gatsby build` it generates a bunch of files and these "data" were not being added in the `setup.py` file. I have done a few more things in my PR. The following attempts to summarize it.
* Update setup files such that the built assets are not ignored during the installation
* Fix the logo issue by loading it via [static query](https://www.gatsbyjs.com/blog/2019-02-20-introducing-use-static-query/) rather than hosting it in `app.py`
* Added a "time taken column" in the table

**Comment by koaning** [comment]
https://github.com/koaning/skedulord/pull/36
