### ISSUE TITLE
Skedulord + python-crontab?

### ISSUE THREAD

**Issue by samarpan-rai** [koaning/skedulord#33]
Just an idea, how about we make skedulord talk with [python-crontab](https://pypi.org/project/python-crontab/)? It's my personal problem that I don't know if my tasks have run successfully. I know the goal of this repo is to not re-invent the whole scheduling stuff but what if we could at least provide an interface for it? For example, everytime `python-crontab` notices that a job has run, it could send inform skedulord. What do you guys think?

**Comment by koaning** [comment]
This is actually stuff I'm working on right now. 

I'm taking the time to do a *big* overhaul of a lot of things though. 

Mainly -> I want to remove the frontend and replace it with rich.

**Comment by koaning** [comment]
https://github.com/koaning/skedulord/pull/36
